spring.application.name=Prj016_paesi_del_mondo-2



spring.datasource.url=jdbc:sqlserver://SWD-2325-27\SQLEXPRESS:1433;DatabaseName=Paesi
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
server.port=9131