spring.application.name=prodotti

spring.datasource.url=jdbc:mysql://localhost/java
spring.datasource.username=root
spring.datasource.password=
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update